# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swearjar}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hull", "Jeff Vyduna"]
  s.date = %q{2011-04-13}
  s.description = %q{Put another nickel in the swearjar. Simple profanity detection with content analysis.}
  s.email = %q{geeks@polleverywhere.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "config/en.yml",
    "lib/swearjar.rb",
    "lib/swearjar/tester.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/swearjar_spec.rb"
  ]
  s.homepage = %q{http://github.com/polleverywhere/swearjar}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Put another nickel in the swearjar. Simple profanity detection with content analysis.}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/swearjar_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fuzzyhash>, [">= 0.0.11"])
      s.add_runtime_dependency(%q<dirge>, [">= 0.0.3"])
    else
      s.add_dependency(%q<fuzzyhash>, [">= 0.0.11"])
      s.add_dependency(%q<dirge>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<fuzzyhash>, [">= 0.0.11"])
    s.add_dependency(%q<dirge>, [">= 0.0.3"])
  end
end

